= Core Interface

== ClientRegistration
ClientRegistration是向OAuth 2.0或OpenID Connect 1.0提供程序注册的客户端的表示.

客户端注册包含信息, 例如客户端ID, 客户端密钥, 授权授予类型, 重定向URI, 作用域,授权URI, 令牌URI和其他详细信息.

ClientRegistration及其属性定义如下:

.ClientRegistration.java
[source,java]
----
public final class ClientRegistration implements Serializable {
	private static final long serialVersionUID = SpringSecurityCoreVersion.SERIAL_VERSION_UID;
    // 在我们系统中的唯一标识, 我们的系统可能有集成了多个 OAuthServer. 如Github, Google, Facebook
	private String registrationId;
    // 这个是我们在第三方平台注册时应用时, 平台给我们的 ClientId 以及 ClientSecret
	private String clientId;
	private String clientSecret;
    //
	private ClientAuthenticationMethod clientAuthenticationMethod = ClientAuthenticationMethod.BASIC;
	private AuthorizationGrantType authorizationGrantType;
    //
	private String redirectUriTemplate;
	private Set<String> scopes = Collections.emptySet();

    //
	private ProviderDetails providerDetails = new ProviderDetails();
    // 描述性的文字, 该名称可能在某些情况下使用, 例如在自动生成的登录页面中显示客户端名称时.
	private String clientName;

    // 省略getter和toString(), 没有setter, 私有化构造器, 提高内部类Builder. 保证这个类实例创建后无法被外界修改.
	private ClientRegistration() {
	}

	public class ProviderDetails implements Serializable {
		private static final long serialVersionUID = SpringSecurityCoreVersion.SERIAL_VERSION_UID;
        // 授权服务器的授权端点 URI.
		private String authorizationUri;
        // 授权服务器的 Token 端点 URI.
		private String tokenUri;
        //
		private UserInfoEndpoint userInfoEndpoint = new UserInfoEndpoint();
        // 用于从授权服务器检索JSON Web密钥(JWK)的URI,
        // 其中包含用于验证ID令牌的JSON Web签名(JWS)以及可选的用户信息响应加密密钥
		private String jwkSetUri;

        // OpenID 提供程序配置信息. 
        //仅当配置了Spring Boot2.X属性 spring.security.oauth2.client.provider.[providerId].issuerUri时, 此信息才可用
		private Map<String, Object> configurationMetadata = Collections.emptyMap();

        // 一样只提供了getter.
		private ProviderDetails() {
		}


		public class UserInfoEndpoint implements Serializable {
			private static final long serialVersionUID = SpringSecurityCoreVersion.SERIAL_VERSION_UID;
            // UserInfo 端点的URI, 用于访问经过身份验证的最终用户的属性.
			private String uri;
            // 请求用户信息时如何携带访问Token, 默认值 Header(请求头), 还支持 Form(表单), Query(查询参数)
			private AuthenticationMethod authenticationMethod = AuthenticationMethod.HEADER;
            // 从UserInfo端点返回的属性的名称, 这个名称是最终用户的标识.
			private String userNameAttributeName;

            // 一样只提供了getter
			private UserInfoEndpoint() {
			}
		}
	}
}
----

== ClientRegistrationRepository
充当OAuth2.0/OpenID Connect 1.0 ClientRegistration的存储库.

Client registration 信息最终由关联的授权服务器存储和拥有. 
此存储库提供了检索与授权服务器一起存储的主要客户端注册的子集的功能.

[source,java]
----
public interface ClientRegistrationRepository {

	/**
	 * Returns the client registration identified by the provided {@code registrationId}, or {@code null} if not found.
	 *
	 */
	ClientRegistration findByRegistrationId(String registrationId);

}
----

TIP: ``ClientRegistrationRepository``的默认实现是``InMemoryClientRegistrationRepository``.


自动配置还会在``ApplicationContext``中将``ClientRegistrationRepository``作为Bean注册,
以便在应用程序需要时可用于依赖项注入.

[source,java]
----
@Controller
public class OAuth2ClientController {

    @Autowired
    private ClientRegistrationRepository clientRegistrationRepository;

    @GetMapping("/")
    public String index() {
        ClientRegistration oktaRegistration =
            this.clientRegistrationRepository.findByRegistrationId("okta");

        ...

        return "index";
    }
}
----

== OAuth2AuthorizedClient

``OAuth2AuthorizedClient``是授权客户端的表示. 
当最终用户(资源所有值)已向客户端授予访问其受保护资源的权限时,
则认为该客户端已经被授权.

``OAuth2AuthorizedClient``的作用是将``OAuth2AccessToken``和``可选的OAuth2RefreshToken``
与``ClientRegistration``和资源所有者相关联,

[source,java]
----
public class OAuth2AuthorizedClient implements Serializable {
	private static final long serialVersionUID = SpringSecurityCoreVersion.SERIAL_VERSION_UID;
	private final ClientRegistration clientRegistration;
	private final String principalName;
	private final OAuth2AccessToken accessToken;
	private final OAuth2RefreshToken refreshToken;

	public OAuth2AuthorizedClient(ClientRegistration clientRegistration, String principalName, OAuth2AccessToken accessToken) {
		this(clientRegistration, principalName, accessToken, null);
	}

	public OAuth2AuthorizedClient(ClientRegistration clientRegistration, String principalName,
									OAuth2AccessToken accessToken, @Nullable OAuth2RefreshToken refreshToken) {
		Assert.notNull(clientRegistration, "clientRegistration cannot be null");
		Assert.hasText(principalName, "principalName cannot be empty");
		Assert.notNull(accessToken, "accessToken cannot be null");
		this.clientRegistration = clientRegistration;
		this.principalName = principalName;
		this.accessToken = accessToken;
		this.refreshToken = refreshToken;
	}

	public ClientRegistration getClientRegistration() {
		return this.clientRegistration;
	}

	public String getPrincipalName() {
		return this.principalName;
	}

	public OAuth2AccessToken getAccessToken() {
		return this.accessToken;
	}

	public @Nullable OAuth2RefreshToken getRefreshToken() {
		return this.refreshToken;
	}
}
----


== OAuth2AuthorizedClientRepository/OAuth2AuthorizedClientService 

``OAuth2AuthorizedClientRepository``负责在Web请求之间保存 ``OAuth2AuthorizedClient``.
而``OAuth2AuthorizedClientService``的主要作用是在应用程序级别管理``OAuth2AuthorizedClient``

从开发人员的角度来看, ``OAuth2AuthorizedClientRepository``或``OAuth2AuthorizedClientService``
提供了查找与客户端关联的``OAuth2AcessToken``的功能, 以便可以将用于发起受保护的资源请求.

.OAuth2AuthorizedClientRepository.java
[source,java]
----
public interface OAuth2AuthorizedClientRepository {
	<T extends OAuth2AuthorizedClient> T loadAuthorizedClient(String clientRegistrationId, Authentication principal,
																HttpServletRequest request);

	void saveAuthorizedClient(OAuth2AuthorizedClient authorizedClient, Authentication principal,
								HttpServletRequest request, HttpServletResponse response);

	void removeAuthorizedClient(String clientRegistrationId, Authentication principal,
								HttpServletRequest request, HttpServletResponse response);
}
----

.OAuth2AuthorizedClientService.java
[source,java]
----
// 默认实现是 InMeoryOAuth2AuthorizedClientService
public interface OAuth2AuthorizedClientService {

	<T extends OAuth2AuthorizedClient> T loadAuthorizedClient(String clientRegistrationId, String principalName);

	void saveAuthorizedClient(OAuth2AuthorizedClient authorizedClient, Authentication principal);

	void removeAuthorizedClient(String clientRegistrationId, String principalName);

}
----

从开发人员的角度来看, ``OAuth2AuthorizedClientRepository``或``OAuth2AuthorizedClientService``
提供了查找与客户端关联的``OAuth2AccessToken``的功能, 以便可以将其用于发起受保护的资源请求.

可以项下面一样使用:
[source,java]
----
@Controller
public class OAuth2ClientController {

    @Autowired
    private OAuth2AuthorizedClientService authorizedClientService;

    @GetMapping("/")
    public String index(Authentication authentication) {
        OAuth2AuthorizedClient authorizedClient =
            this.authorizedClientService.loadAuthorizedClient("okta", authentication.getName());

        OAuth2AccessToken accessToken = authorizedClient.getAccessToken();

        //...

        return "index";
    }
}
----

== OAuth2AuthorizedClientManager/OAuth2AuthorizedClientProvider 

``OAuth2AuthorizedClientManager``负责``OAuth2AuthorizedCilent``的整体管理. 
主要职责包括:

1. 使用OAuth2AuthorizedClientProvider授权(或重新授权)OAuth2.0客户端.
2. 委托OAuth2AuthorizedClient的持久性, 通常使用``OAuth2AuthorizedClientService``或``OAuth2AuthorizedClientRepository``

OAuth2AuthorizedClientProvider实施用于授权(或者重新授权)OAuth2.0客户端的策略. 实施通常将实施授权授予类型, 例如授权码, 客户端凭证等.

.OAuth2AuthorizedClientManager.java
[source,java]
----
public interface OAuth2AuthorizedClientManager {

    //
	OAuth2AuthorizedClient authorize(OAuth2AuthorizeRequest authorizeRequest);

}
----

.OAuth2AuthorizedClientProvider.java
[source,java]
----
public interface OAuth2AuthorizedClientProvider {

	@Nullable
	OAuth2AuthorizedClient authorize(OAuth2AuthorizationContext context);

}
----

== Authorization Grant Support


