= Overview

``Quartz``是功能强大的开源作业调度库, 几乎可以集成到任何Java应用程序中.

``Quartz``可用于创建简单或复杂的计划, 以执行数以万计的工作.


== The Quratz API, Jobs And Triggers

=== core abstract

* Scheduler - the main API for interacting(互动) with the scheduler 
* Job - an interface to be implemented by components that you wish to have executed by the scheduler.
* JobDetail - used to define instances of Jobs.
* Trigger - a component that defines the schedule upon which a given Job will be executed.
* JobBuilder - used to define/build JobDetail instances, which define instances of Jobs.
* TriggerBuilder - used to define/build JobDetail instances, which define instances of Jobs.

.主要提供的DSL支持
[source,java]
----
import static org.quartz.JobBuilder.*;
import static org.quartz.SimpleScheduleBuilder.*;
import static org.quartz.CronScheduleBuilder.*;
import static org.quartz.CalendarIntervalScheduleBuilder.*;
import static org.quartz.TriggerBuilder.*;
import static org.quartz.DateBuilder.*;
----


==== Jobs and Triggers
A Job is a class that implements the Job interface,
which has only one simple method:

.org.quartz.Job.java
[source,java]
----
package org.quartz;

public interface Job {
    public void execute(JobExecutionContext context) throw JobExecutionException;
}
----

当 Job 的 Trigger 触发时, execute() 方法将有 Scheduler 的工作线程之一调用.
传递给此方法的``JobExecutionContext``对象为作业实例提供有关其``runtime``环境信息如:
执行这个Job的Scheduler句柄, 触发这个任务的Trigger句柄, Job的``JobDetail``对象, 以及其他的一些项目.

``JobDetail``对象是将作业添加到调度程序时由QuartzClient(我们的app)创建的.
它包含Job的各种属性设置以及``JobDataMap``, 可用户存储给定Job类实例的状态信息.
它本质上是作业实例的定义.(就像Spring中的 BeanDefinition 抽象一样, 携带Bean的各种信息)

``Trigger``对象用于触发Job的执行. 当你希望安排Job时, 可以实例化``Trigger``并调整其属性以提供希望的安排.
``Trigger``还可能具有与之关联的JobDataMap, 这对于将特定的Trigger触发的参数传递给Job很有用.
Quartz附带了几种不同的触发器类型, 但是最有用的类型是``SimpleTrigger``和``CronTrigger``

``SimpleTrigger``是间隔多久触发一次的触发器, 而``CronTrigger``是基于日历的触发器, 可以指定具体某天触发.
